services:
  webapp:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        NODE_ENV: ${NODE_ENV} # Pass the NODE_ENV to the Dockerfile        
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - PODSLEEP=${PODSLEEP}
    container_name: webapp
    ports:
      - "8000:8000"    
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
